# Generated by Django 6.0 on 2026-05-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinventory',
            options={'ordering': ['-created_at']},
        ),
    ]
